services:
  db:
    image: mariadb:10.11
    container_name: pma_marmits_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      pma_marmits:
        ipv4_address: ${IPV4_DB:-192.168.7.3}


  ssh-tunnel:
    build: 
      context: .
      dockerfile: Dockerfile
      target: tunnel_ssh
    container_name: mariadb-ssh-tunnel
    restart: unless-stopped
    environment:
      SSH_USER: ${SSH_USER}
      SSH_HOST: ${SSH_HOST}
      SSH_PORT: ${SSH_PORT}
      LOCAL_PORT: ${LOCAL_PORT}
      REMOTE_HOST: ${REMOTE_HOST}
      REMOTE_PORT: ${REMOTE_PORT}
    volumes:
      - ${SSH_KEY_PATH}:/root/.ssh/id_ed25519:ro
    networks:
      pma_marmits:
        ipv4_address: ${IPV4_SSH_TUNNEL:-192.168.7.4}

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_marmits_phpmyadmin
    restart: always    
    ports:
      - 9080:80
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - LOCAL_PORT=${LOCAL_PORT}
    networks:
      pma_marmits:
        ipv4_address: ${IPV4_PM:-192.168.7.2}

networks:
  pma_marmits:
    name: pma_marmits
    driver: bridge
    ipam:
      config:
        - subnet: ${IPV4_SUBNET:-192.168.7.0/24}
          gateway: ${IPV4_GATEWAY:-}